### ISSUE TITLE
Init:CrashLoopBackOff in ml-centraleventprocessor

### ISSUE THREAD

**Issue by pyephyoeaung** [tdaly61/mini-loop#16] opened 2022-08-07 17:34 UTC
helm installation failed and getting CrashLoopBackOff in ml-centraleventprocessor pod.

`vagrant@ubuntu-focal:~$ kubectl logs  ml-centraleventprocessor-6656cd6cd-hgl4m -c wait-for-mongodb 
sh: 1: mongo: not found
`

> vagrant@ubuntu-focal:~$ kubectl describe pod  ml-centraleventprocessor-6656cd6cd-hgl4m
Name:         ml-centraleventprocessor-6656cd6cd-hgl4m
Namespace:    default
Priority:     0
Node:         ubuntu-focal/10.0.2.15
Start Time:   Sun, 07 Aug 2022 16:47:17 +0000
Labels:       app.kubernetes.io/instance=ml
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=centraleventprocessor
              app.kubernetes.io/version=11.0.3
              helm.sh/chart=centraleventprocessor-11.0.3
              pod-template-hash=6656cd6cd
Annotations:  checksum/config: dd1329c22f208a2fc6e83d3f74983f1f06d3e7ffcd42fcc5e647b78e3cda037c
              cni.projectcalico.org/podIP: 10.1.223.180/32
              cni.projectcalico.org/podIPs: 10.1.223.180/32
Status:       Pending
IP:           10.1.223.180
IPs:
  IP:           10.1.223.180
Controlled By:  ReplicaSet/ml-centraleventprocessor-6656cd6cd
Init Containers:
  wait-for-mongodb:
    Container ID:  containerd://0b5a340e09f8deef1710f5cc053f03743539f4624c44463e2207a8a7b0567daf
    Image:         bitnami/mongodb:latest
    Image ID:      docker.io/bitnami/mongodb@sha256:722dd089679822bf321824301878ebe02209b1662b27ec67c06a39e90221beea
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      mongo mongodb://ml-cep-mongodb:27017 --eval "db.adminCommand('ping')"
    State:          Terminated
      Reason:       Error
      Exit Code:    127
      Started:      Sun, 07 Aug 2022 17:33:39 +0000
      Finished:     Sun, 07 Aug 2022 17:33:39 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    127
      Started:      Sun, 07 Aug 2022 17:28:36 +0000
      Finished:     Sun, 07 Aug 2022 17:28:36 +0000
    Ready:          False
    Restart Count:  14
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mlrpw (ro)
  wait-for-kafka:
    Container ID:  
    Image:         solsson/kafka:latest
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until ./bin/kafka-broker-api-versions.sh --bootstrap-server ml-kafka:9092; do echo waiting for Kafka; sleep 2; done;
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mlrpw (ro)
Containers:
  centraleventprocessor:
    Container ID:   
    Image:          mojaloop/central-event-processor:v11.0.2
    Image ID:       
    Port:           3080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:3080/health delay=30s timeout=1s period=15s #success=1 #failure=3
    Readiness:      http-get http://:3080/health delay=30s timeout=1s period=15s #success=1 #failure=3
    Environment:
      LOG_LEVEL:          info
      CSL_LOG_TRANSPORT:  file
    Mounts:
      /opt/central-event-processor/config from ml-centraleventprocessor-config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mlrpw (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ml-centraleventprocessor-config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ml-centraleventprocessor-config
    Optional:  false
  default-token-mlrpw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-mlrpw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  46m                  default-scheduler  Successfully assigned default/ml-centraleventprocessor-6656cd6cd-hgl4m to ubuntu-focal
  Normal   Pulled     44m (x5 over 46m)    kubelet            Container image "bitnami/mongodb:latest" already present on machine
  Normal   Created    44m (x5 over 46m)    kubelet            Created container wait-for-mongodb
  Normal   Started    44m (x5 over 46m)    kubelet            Started container wait-for-mongodb
  Warning  BackOff    76s (x211 over 46m)  kubelet            Back-off restarting failed container

**Comment by pye-aung** [comment] 2022-08-09 08:52
I found the similar issue https://github.com/bitnami/containers/issues/2062
This is because of remove mongo command in latest release
https://www.mongodb.com/docs/manual/release-notes/6.0-compatibility/#legacy-mongo-shell-removed.

The issue is resolved after changing wait-for-mongodb image version to 5.0.9.

**Comment by tdaly61** [comment] 2022-08-10 21:42
hi @pyephyoeaung @pye-aung , is this issue with version 4.0 of mini-loop ?  I think this issue is fixed in version 4.0

**Comment by pye-aung** [comment] 2022-08-11 02:50
Hi, 4.0 of mini-loop version has the same issue. Could you please check and update?
https://github.com/tdaly61/mini-loop/blob/master/install/mini-loop/etc/miniloop_values.yaml#L3123

**Comment by tdaly61** [comment] 2022-08-11 22:45
@pye-aung I get k logs ml-centraleventprocessor-d67f44958-n98hw -c wait-for-mongodb
{"t":{"$date":"2022-08-11T22:22:57.265Z"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"-","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":13},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":13},"outgoing":{"minWireVersion":0,"maxWireVersion":13},"isInternalClient":false}}}
MongoDB shell version v5.0.9
connecting to: mongodb://ml-cep-mongodb:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("9a3d0eee-9802-4914-a593-a5c8fdbe012b") }
MongoDB server version: 5.0.9
{ "ok" : 1 }

Also with mini-loop v4 the etc/miniloop_values.yaml file is not used for the deployment of mojaloop. Instead in v4.0 the values file  in the ~helm/mojaloop directory should be used and this file should have been automatically modified by the mini-loop scripts/mod_local_miniloop.py.  Also and I think importantly all of the requirements.yaml files should be updated and this is where I update the mongo chart version.  I am guessing if you look in the /tmp/miniloop-install.log and /tmp/miniloop-install.err files , we might find the mod_local_miniloop.py. had errors.

**Comment by tdaly61** [comment] 2023-02-23 02:03
hey @pye-aung , I think I fixed this ages ago.  Do you agree ?  can I close this issue ? ..thanks

**Comment by pye-aung** [comment] 2023-02-24 07:44
Sure, you can close this issue.

**Closed** 2023-03-02 07:20 UTC
